version: "3.8"
services:
  northwinddb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: northwinddb
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - northwinddb_volume:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password12*
    networks:
      - northwindnet
  northwind.api:
    image: nothwind_api
    container_name: northwind.api
    build:
      context: ..
      dockerfile: NorthwindSample/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Sql=Server=northwinddb,1433;Initial Catalog=Northwind;User ID=sa;Password=Password12*;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"  
    ports:
      - "5010:80"
    networks:
      - northwindnet
    depends_on:
      - northwinddb
      
volumes:
  northwinddb_volume:

networks:
  northwindnet:
    driver: bridge